name: Build and Release

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      tag:
        description: 'Tag name'
        required: true
      note:
        description: 'Release note'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies and build
        run: |
          npm install -g @vercel/ncc
          npm install @actions/github
          npm run build
      
      - name: Commit changes
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'TzuChiaWang'
          git config --global user.email '152773519+TzuChiaWang@users.noreply.github.com'
          git add .
          git commit -m "dist build"
          git push https://TzuChiaWang:${{ secrets.ACTIONSECRETSTOKEN }}@github.com/TzuChiaWang/TextEditor.git

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      
      - name: Test index.js
        env:
          INPUT_GITHUB_USERNAME: "TzuChiaWang"
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TARGET_REPOS: '[TzuChiaWang/TextEditor]'
          INPUT_OUTPUT_STYLE: MARKDOWN
          INPUT_IGNORE_EVENTS: '[]'
          INPUT_README_PATH: README.md
          INPUT_COMMIT_MESSAGE: Update README.md
          INPUT_EVENT_LIMIT: '100'
        run: |
          node ./dist/index.js

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Pull latest changes
        run: |
          git config --global user.name 'TzuChiaWang'
          git config --global user.email '152773519+TzuChiaWang@users.noreply.github.com'
          git pull
      
      - name: Create and push tag
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "${{ github.event.inputs.note }}"
          git push origin ${{ github.event.inputs.tag }}
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.note }}
          draft: false
          prerelease: false
