name: Build and Release

on:
  schedule:
    - cron: "0 0 */14 * *" # Runs every 14 days at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
    update-activity:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Build and Release
          uses: TzuChiaWang/activity-log@Release v3
          with:
            GITHUB_USERNAME: "TzuChiaWang"
            GITHUB_TOKEN: ${{ secrets.ACTIONSECRETSTOKEN }} # Ensure this matches the secret name in repository settings  
